substitutions:
  name: "mini-switch"
  friendly_name: "Mini Switch"
  project_name: "theemm.mini-switch"
  project_version: "1.0"
  light_restore_mode: RESTORE_DEFAULT_ON
  
esphome:
  name: "${name}"
  name_add_mac_suffix: false
  project:
    name: "${project_name}"
    version: "${project_version}"
  build_path: "builds/${name}.bin"

esp8266:
  board: esp8285
  restore_from_flash: true
  
logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: "${name}.local"

  ap:
    ssid: "${name}-rescue"
    password: !secret ap_ppassword

web_server:
  port: 80

captive_portal: