substitutions:
  light_restore_mode: "RESTORE_DEFAULT_OFF"

esphome:
  name: "${name}"
  name_add_mac_suffix: false
  project:
    name: "${project_name}"
    version: "${project_version}"
  build_path: "builds/${name}"

esp8266:
  board: esp8285

logger:

ota:
  password: !secret ota_password

wifi:
  use_address: "${name}.theemm.com"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "${name}"
    password: !secret ap_ppassword
    channel: 1
    manual_ip:
      static_ip: 192.168.1.1
      gateway: 192.168.1.1
      subnet: 255.255.255.0

web_server:
  port: 80

mqtt:
  broker: mqtt.theemm.com
  username: mr_mqtt
  password: !secret mqtt_password
  log_topic: logs
  discovery: true

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
